-
    name: Copy file to target servers and do some more things
    hosts: all
    tasks:
      - name: Copy file
        copy: 
          src: /tmp/test-file.txt
          dest: /tmp/test-file.txt
      - name: Run the Date Command
        command: date
      - name: Execute a command to display hosts file
        command: cat /etc/hosts
-
    name: Install Updates via Yum
    hosts: all
    tasks:
        - name: Install Updates via Yum
          yum: name=* state=latest