-
    name: Copy file to target servers and do some more things
    hosts: all
    tasks:
      - name: Copy file
        copy: 
          src: /tmp/test-file.txt
          dest: /tmp/test-file.txt
      - name: Run the Date Command
        command: date
      - name: Execute a command to display hosts file
        command: cat /etc/hosts
-
    name: Install Updates via Yum
    hosts: all
    tasks:
        - name: check packages for updates
          shell: yum list updates | awk 'f;/Updated Packages/{f=1;}' | awk '{ print $1 }'
          changed_when: updates.stdout_lines | length > 0
          args:
            warn: false
          register: updates
        - name: display count
          debug:
            msg: "Found {{ updates.stdout_lines | length }} packages to be updated:\n\n{{ updates.stdout }}"
        - when: updates.stdout_lines | length > 0
          block:
            - name: install updates using yum
              yum:
                name: "*"
                state: latest
            - name: install yum-utils
              package:
                name: yum-utils
            - name: check if reboot is required
              shell: needs-restarting -r
              failed_when: false
              register: reboot_required
              changed_when: false

        - when: updates.stdout_lines | length > 0 and reboot_required.rc != 0
          block:
            - name: reboot the server if required
              shell: sleep 3; reboot
              ignore_errors: true
              changed_when: false
              async: 1
              poll: 0
            - name: wait for server to come back after reboot
              wait_for_connection:
                timeout: 600
                delay: 20
              register: reboot_result
            - name: reboot time
              debug:
                msg: "The system rebooted in {{ reboot_result.elapsed }} seconds."

